/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolab;

/**
 *
 * @author miche
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    Pacientes pPacientes = new Pacientes();
    Facturacion pFacturacion = new Facturacion();
    Estudio pEstudio = new Estudio();
    Usuarios pUsuarios = new Usuarios();
    MobyEquipo pMobEquipo = new MobyEquipo();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        LabelPaciente = new javax.swing.JLabel();
        LabelFacturas = new javax.swing.JLabel();
        LabelEstudio = new javax.swing.JLabel();
        LabelUsuarios = new javax.swing.JLabel();
        LabelMobYEquipo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("framePrincipal"); // NOI18N
        setUndecorated(true);

        PanelPrincipal.setBackground(new java.awt.Color(102, 204, 255));

        LabelPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WheelchairNpng.png"))); // NOI18N
        LabelPaciente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LabelPacienteMouseMoved(evt);
            }
        });
        LabelPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelPacienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelPacienteMouseExited(evt);
            }
        });

        LabelFacturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bill_104N.png"))); // NOI18N
        LabelFacturas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LabelFacturasMouseMoved(evt);
            }
        });
        LabelFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelFacturasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelFacturasMouseExited(evt);
            }
        });

        LabelEstudio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEstudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heart MonitorN.png"))); // NOI18N
        LabelEstudio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LabelEstudioMouseMoved(evt);
            }
        });
        LabelEstudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelEstudioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelEstudioMouseExited(evt);
            }
        });

        LabelUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add UserNpng.png"))); // NOI18N
        LabelUsuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LabelUsuariosMouseMoved(evt);
            }
        });
        LabelUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelUsuariosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelUsuariosMouseExited(evt);
            }
        });

        LabelMobYEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMobYEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BedN.png"))); // NOI18N
        LabelMobYEquipo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LabelMobYEquipoMouseMoved(evt);
            }
        });
        LabelMobYEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelMobYEquipoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelMobYEquipoMouseExited(evt);
            }
        });

        jLabel6.setText("Mobiliario y Equipo");

        jLabel7.setText("Pacientes");

        jLabel8.setText("Facturación");

        jLabel9.setText("Estudio");

        jLabel10.setText("Personal");

        jLabelSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CancelB.png"))); // NOI18N
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(207, 207, 207)
                .addComponent(jLabel6)
                .addGap(188, 188, 188))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(LabelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(LabelMobYEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel7)
                .addGap(151, 151, 151)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(126, 126, 126))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(LabelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(LabelFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(LabelEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(LabelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(LabelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(61, 61, 61))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelMobYEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(62, 62, 62))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelSalirMouseClicked

    private void LabelUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelUsuariosMouseClicked
        pUsuarios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelUsuariosMouseClicked

    private void LabelPacienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelPacienteMouseMoved
        LabelPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_LabelPacienteMouseMoved

    private void LabelPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelPacienteMouseExited
        LabelPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,204,255)));
    }//GEN-LAST:event_LabelPacienteMouseExited

    private void LabelFacturasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelFacturasMouseMoved
        LabelFacturas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
                                            
    }//GEN-LAST:event_LabelFacturasMouseMoved

    private void LabelFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelFacturasMouseExited
        LabelFacturas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,204,255)));
    }//GEN-LAST:event_LabelFacturasMouseExited

    private void LabelEstudioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEstudioMouseMoved
        LabelEstudio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_LabelEstudioMouseMoved

    private void LabelEstudioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEstudioMouseExited
        LabelEstudio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,204,255)));
    }//GEN-LAST:event_LabelEstudioMouseExited

    private void LabelUsuariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelUsuariosMouseMoved
        LabelUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_LabelUsuariosMouseMoved

    private void LabelUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelUsuariosMouseExited
        LabelUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,204,255)));
    }//GEN-LAST:event_LabelUsuariosMouseExited

    private void LabelPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelPacienteMouseClicked
        pPacientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelPacienteMouseClicked

    private void LabelFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelFacturasMouseClicked
        pFacturacion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelFacturasMouseClicked

    private void LabelEstudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelEstudioMouseClicked
        pEstudio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelEstudioMouseClicked

    private void LabelMobYEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMobYEquipoMouseClicked
        pMobEquipo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelMobYEquipoMouseClicked

    private void LabelMobYEquipoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMobYEquipoMouseMoved
        LabelMobYEquipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_LabelMobYEquipoMouseMoved

    private void LabelMobYEquipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelMobYEquipoMouseExited
        LabelMobYEquipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,204,255)));
    }//GEN-LAST:event_LabelMobYEquipoMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEstudio;
    private javax.swing.JLabel LabelFacturas;
    private javax.swing.JLabel LabelMobYEquipo;
    private javax.swing.JLabel LabelPaciente;
    private javax.swing.JLabel LabelUsuarios;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSalir;
    // End of variables declaration//GEN-END:variables
}
